version: '3.3'

services:

  # application API service
  wire-api:
    # a name we want our container to be named.
    container_name: wire-api

    image: wire-api-v1:v1
    build:
      context: ./api
      dockerfile: Dockerfile

    volumes:
      - ${LOCAL_REPO_DIRECTORY}:/wire

    ports:
    # mapping the container port 5000 to the host port locally on my computer 5001
      - 3000:3000

    depends_on:
    # this makes this service to wait for the amity_db service to come up first before it runs
      - wire-db

    links:
    # this links this service to the amity_db service
      - wire-db

    
  # postgresql database server service
  wire-db:

    # container name.
    container_name: wire-db

    image: wire-db-v1:v1
    build:
      context: ./database
      dockerfile: Dockerfile

    ports:
      - 5432:5432


