# #############################################################################
# # service that links the internet to the frontend


# apiVersion: v1
# kind: Service
# metadata:
#   name: wire-frontend-service-to-frontend
#   labels:
#     app: wire-frontend-service-to-frontend
# spec:
#   ports: 
#   - port: 8080
#     targetPort: 8080
#     protocol: TCP
#   selector:
#     app: wire-frontend


# --- 

###########################################################################
# service that links the frontend and the api


apiVersion: v1
kind: Service
metadata:
  name: wire-service-to-api
  labels:
    run: wire-service-to-api
spec:
  ports:
  - port: 3000

    protocol: TCP
  selector:
    run: wire-api
  type: LoadBalancer


---


#####################################################################################
# service that links the api to the database


apiVersion: v1
kind: Service
metadata:
  name: wire-api-service-to-db
  labels:
    app: wire-api-service-to-db
spec:
  ports: 
  - port: 5432

    protocol: TCP
  selector:
    run: wire-db
  type: NodePort



